// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWcIMy6hBF4aP6LTSS1PwtmZogUebAI4A',
    appId: '1:624993566775:web:5b1b72cb58203b46123fb2',
    messagingSenderId: '624993566775',
    projectId: 'canemap-system',
    authDomain: 'canemap-system.firebaseapp.com',
    databaseURL: 'https://canemap-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'canemap-system.firebasestorage.app',
    measurementId: 'G-08KFJQ1NEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU0akDUS9cSXl6e6vC7udfKiE_Bsqt8rI',
    appId: '1:624993566775:android:e0a914e018cf96fa123fb2',
    messagingSenderId: '624993566775',
    projectId: 'canemap-system',
    databaseURL: 'https://canemap-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'canemap-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQbSOF470k-cD-dIEuy5dLmDRfoc7u4Q',
    appId: '1:624993566775:ios:68bca0ee87d9c2bc123fb2',
    messagingSenderId: '624993566775',
    projectId: 'canemap-system',
    databaseURL: 'https://canemap-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'canemap-system.firebasestorage.app',
    iosBundleId: 'com.example.canemap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFQbSOF470k-cD-dIEuy5dLmDRfoc7u4Q',
    appId: '1:624993566775:ios:68bca0ee87d9c2bc123fb2',
    messagingSenderId: '624993566775',
    projectId: 'canemap-system',
    databaseURL: 'https://canemap-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'canemap-system.firebasestorage.app',
    iosBundleId: 'com.example.canemap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWcIMy6hBF4aP6LTSS1PwtmZogUebAI4A',
    appId: '1:624993566775:web:be4a5b26aef27097123fb2',
    messagingSenderId: '624993566775',
    projectId: 'canemap-system',
    authDomain: 'canemap-system.firebaseapp.com',
    databaseURL: 'https://canemap-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'canemap-system.firebasestorage.app',
    measurementId: 'G-LH4CMRCNLV',
  );
}
